version: '2.1'
services:
  vnptepay-prepaid-card-service-provider:
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-southeast-1
    #    awslogs-group: echo-service-provider
    #    awslogs-create-group: 'true'
    #    awslogs-multiline-pattern: '(INFO|DEBUG|ERROR|WARNNING)'
    build:
      context: ./
    environment:
      - CARD_SERVICE_ENABLED=YES
      - LOG_LEVEL=debug
      - KAFKA_QUEUE_ENABLED=NO
      - CARD_SERVICE_PROVIDER=VNPTEPAY
    ports:
     - 8100:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
    restart: always