version: '2.1'
services:
  vnptepay-prepaid-card-service-provider:
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-southeast-1
    #    awslogs-group: echo-service-provider
    #    awslogs-create-group: 'true'
    #    awslogs-multiline-pattern: '(INFO|DEBUG|ERROR|WARNNING)'
    build:
      context: ./
    environment:
      - PREPAID_CARD_SERVICE_PROVIDER_ENABLED=YES
      - LOG_LEVEL=debug
      - PREPAID_CARD_SERVICE_PROVIDER=VNPTEPAY
      - PREPAID_CARD_SERVICE_PROVIDER_URL=http://itopup-test.megapay.net.vn:8086/CDV_Partner_Services/services/Interfaces?wsdl
      - PREPAID_CARD_SERVICE_PROVIDER_SECURE_PRIVATE_KEY=vnpt_epay_private_key.pem
      - PREPAID_CARD_SERVICE_PROVIDER_PARTNER_NAME=partnerTest_PHP
      - PREPAID_CARD_SERVICE_PROVIDER_PARTNER_PASSWORD=123456abc
      - PREPAID_CARD_SERVICE_PROVIDER_KEY_SOFPIN=123456abc
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - DYNAMODB_REGION_CODE=ap-southeast-1
      - DYNAMODB_TABLE_NAME=mobile-prepaid-service-tracker
    ports:
     - 8100:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
    restart: always