swagger: '2.0'
info:
  version: 0.0.1
  title: mobile-prepaid-card-service-provider
host: 'localhost:8000'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /orders:
    x-swagger-router-controller: OrdersController
    post:
      description: >-
        Import a batch of mobile prepaid codes into store.
      operationId: ImportItemsOrders
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/AppId'
        - name: body
          in: body
          description: The object description of the list of mobile prepaid cards.
          required: true
          schema:
            $ref: '#/definitions/ImportItemsOrdersRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ImportOrdersResponse'
        default:
          description: Error Occured
          schema:
            $ref: '#/definitions/ErrorResponse'
    get:
      description: >-
        Order a batch of mobile prepaid codes from system with a specific
        amount, quantity and network operation code.
      operationId: GetItemsOrders
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/AppId'
        - $ref: '#/parameters/RequestId'
        - $ref: '#/parameters/Quantity'
        - $ref: '#/parameters/Amount'
        - $ref: '#/parameters/OpCode'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/OrdersResponse'
        default:
          description: Error Occured
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/orders/{id}':
    x-swagger-router-controller: OrderController
    get:
      description: >-
        Get an order tracking details of a specified order. It will return all
        the information about the requested order.
      operationId: getOrderItem
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/OrderId'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/OrderResponse'
        default:
          description: Error Occured
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/orders/{id}/status':
    x-swagger-router-controller: OrderController
    get:
      description: >-
        Get an order tracking status of a specified order. It will return all
        the information about the requested order.
      operationId: getOrderItemStatus
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/OrderId'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/OrdersStatusResponse'
        default:
          description: Error Occured
          schema:
            $ref: '#/definitions/ErrorResponse'
  /provider/inquiry:
    x-swagger-router-controller: ProviderInquiry
    get:
      description: Get provider's inventory stock cards in store
      operationId: countCards
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/OpCode'
        - $ref: '#/parameters/Amount'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ProviderInquiryResponse'
        default:
          description: Error Occured
          schema:
            $ref: '#/definitions/ErrorResponse'

parameters:
  AppId:
    name: app_id
    in: header
    type: string
    description: The app identifier which is using services.
  RequestId:
    name: request_id
    in: query
    type: string
    description: The request id to create an oder.
    required: true
  OrderId:
    name: id
    in: path
    type: string
    description: The order id to receive the order item.
    required: true
  Quantity:
    name: quantity
    in: query
    type: integer
    maximum: 1000
    description: The number of items in an order.
    required: true
  Amount:
    name: amount
    in: query
    type: integer
    default: 10000
    description: The amount of each item in an order.
    required: true
    enum:
      - 10000
      - 20000
      - 50000
      - 100000
      - 200000
      - 500000
  OpCode:
    name: opcode
    in: query
    type: string
    description: The short code of network operation in an order such as VTT|VNP|VNN|VMS.
    required: true
definitions:
  OrdersResponse:
    required:
      - request_id
      - order_id
      - status
      - items
    properties:
      request_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
        description: The request id
      order_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
        description: The reference id as known as order id
      status:
        type: string
        example: SUCCESS|PENDING|FAILED
        description: The code which reflect to request status
      items:
        type: array
        items:
          $ref: '#/definitions/OrderItemResponse'
      message:
        type: string
        example: Unknow Error
        description: The message reflect to status if status is FAILED
  OrderResponse:
    required:
      - request_id
      - order_id
      - status
      - opcode
      - amount
      - quantity
      - app_id
      - action
    properties:
      request_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
        description: The request id
      order_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
        description: The reference id as known as order id
      status:
        type: string
        example: SUCCESS|PENDING|FAILED
        description: The code which reflect to request status
      opcode:
        type: string
        example: VTT
      amount:
        type: integer
        example: 500000
      quantity:
        type: integer
        example: 200
      app_id:
        type: string
        example: FLASH|DAILY
        description: The app identifier which was requested order.
      action:
        type: string
        example: INSERT_CARDS|DOWNLOAD_CARDS|COUNT_CARDS
      message:
        type: string
        example: Unknow Error
        description: The message reflect to status if status is FAILED
  OrdersStatusResponse:
    required:
      - request_id
      - order_id
      - status
    properties:
      request_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
        description: The request id
      order_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
        description: The reference id as known as order id
      status:
        type: string
        example: SUCCESS|PENDING|FAILED
      message:
        type: string
        example: Unknow Error
        description: The message reflect to status if status is FAILED
  OrderItemResponse:
    properties:
      opcode:
        type: string
        example: VTT
      code:
        type: string
        example: 6af6b3fe090e4ae4
      amount:
        type: integer
        example: 100000
      serial:
        type: string
        example: 53835832354
      expire:
        type: string
        example: '2050-12-17 00:00:00'
  ProviderInquiryResponse:
    required:
      - request_id
      - order_id
      - amount
      - quantity
      - opcode
    properties:
      request_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
      order_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
        description: The reference id as known as order id
      quantity:
        type: integer
        example: 1000
        description: The number of inquired cards``
      amount:
        type: integer
        example: 100000
        description: The price unit per card
        enum:
          - 10000
          - 20000
          - 50000
          - 100000
          - 200000
          - 500000
      opcode:
        type: string
        example: VTT
        description: The network operation code such as VTT|VNP|VNN|VMS
      message:
        type: string
        example: Unknow Error
        description: The message reflect to status if status is FAILED
  ImportItemsOrdersRequest:
    required:
      - request_id
      - items
    properties:
      request_id:
        $ref: '#/parameters/RequestId'
      items:
        type: array
        items:
          $ref: '#/definitions/OrderItemResponse'
  ImportOrdersResponse:
    required:
      - request_id
      - order_id
      - status
    properties:
      request_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
      order_id:
        type: string
        example: 434c9cb53bcf4e8e9b03ccdc18884c4d
      status:
        type: string
        example: SUCCESS|PENDING|FAILED
      message:
        type: string
  ErrorResponse:
    required:
      - code
    properties:
      code:
        type: string
      message:
        type: string