swagger: '2.0'
info:
  version: 0.0.1
  title: mobile-prepaid-card-service-provider
host: 'localhost:8000'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/order':
    x-swagger-router-controller: Create new mobile prepaid order
    post:
      description: Create a mobile prepaid order
      operationId: createOrder
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/OrderParameters'
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/OrderResponse'
        default:
          description: Error Occured
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/order/:id':
    x-swagger-router-controller: Get order item by order id
    get:
      description: Check order info by order id 
      operationId: getOrderItem
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/RequestId'
        - $ref: '#/parameters/OrderId'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/OrderItemResponse'
        default:
          description: Error Occured
          schema:
            $ref: '#/definitions/ErrorResponse'
parameters:
  RequestId:
    name: request_id
    in: query
    type: string
    description: The request id to create an oder.
    required: true
  OrderId:
    name: id
    in: path
    type: string
    description: The order id to receive the order item.
    required: true
  OrderParameters:
    name: body
    in: body
    description: The parameters for creating new order
    schema:
      $ref: '#/definitions/OrdersRequest'
definitions:
  OrdersRequest:
    required:
      - request_id
      - quantity
      - amount
      - opcode
    properties:
      request_id:
        type: string
        example: 6af6b3fe-090e-4ae4-9f26-ab2f07b13994
      quantity:
        type: integer
        example: 1000
        description: The number of inquired cards
      amount:
        type: integer
        example: 100000
        description: The price unit per card
        enum:
          - 10000
          - 20000
          - 50000
          - 100000
          - 200000
          - 500000
      opcode:
        type: string
        example: VTT
        description: The network operation code such as VTT|VNP|VNN|VMS
  OrderResponse:
    required:
      - request_id
      - order_id
      - status
      - items
    properties:
      request_id:
        type: string
        example: 6af6b3fe-090e-4ae4-9f26-ab2f07b13994
        description: The request id
      order_id:
        type: string
        example: c9d7c073-2634-4350-bc67-eea10c43a64b
        description: The reference id as known as order id
      status:
        type: string
        example: SUCCESS|PENDING|FAIL
      items:
        type: array
        items:
            $ref: '#/definitions/OrderItemResponse'
  OrderItemResponse:
    properties:
      opcode:
        type: string
        example: VTT
      code:
        type: string
        example: 6af6b3fe090e4ae4
      status:
        type: string
        example: SUCCESS|PENDING|FAIL
        description: The code which reflect to request status
  ErrorResponse:
    required:
      - status
    properties:
      status:
        type: string
        example: SUCCESS|PENDING|FAIL
      message:
        type: string